### ISSUE TITLE
some questions？

### ISSUE THREAD

**Issue by fenghuan1994** [Mayochun/Hackintosh-Deskmini310#19]
1.这个引导可以升级MACOS14吗？
2.你有没有遇到bios的时间比系统时间慢8小时的问题。我修改过bios时间，但是进系统后，重启进bios查看，时间又慢了8小时。

1. Can this boot be upgraded MACOS14?
2. Have you ever encountered the problem that the BIOS time is 8 hours slower than the system time. I modified the BIOS time, but after entering the system, I rebooted into the BIOS to view, and the time was 8 hours slower.

1.このブートはMACOS14アップグレードできますか?
2. BIOS時間がシステム時間より8時間遅いという問題に遭遇したことがありますか。 BIOS時間を変更しましたが、システムに入った後、BIOSを再起動して表示すると、時間が8時間遅くなりました。

**Comment by Tsubakimochi** [comment]
1.I can't test MacOS14, so I haven't tested it yet, but I think WiFi will not work because Kext for IntelWiFi card is for Ventura only!
2.Yes, I have confirmed a 9 hour discrepancy on my end. The expected discrepancy is based on UTC. I tried to find out how to correct it, but I couldn't.

**Comment by fenghuan1994** [comment]
Thanks！
